### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by baazouziwiem** [robjweiss/Epinions-Network-Analysis#1]
can you give me the link of your dataset "Epinions_ small.csv"

**Comment by robjweiss** [comment]
You should be able to find it under the `data` folder

**Comment by baazouziwiem** [comment]
Dear Mr

I am a student research master degree "Smart Systems" at the National
School of Computer Science. I am implementing my project of memory under
the title "systems of recommendation based on the confidence". I write in
connection with your work on the site "GitHub" , I am satisfied by your
competence I apreciate you for your hard work.
Can you please show me the execution steps because I am beginner so if
possible can you explain some of your codes because it is not shown in your
work. Could you please send me a tutorial or an explanatory code as well as
my goal to compute a similarity by collaborative filtering and then compare
with calculate a similarity based on trust in order to represent as a
graph. I really appreciate your time and guidance



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
26/04/19
à 03:01:19

**Comment by robjweiss** [comment]
Sure, here's some steps you can follow:

- You need to install git or GitHub
- Then you can clone or download the code from the repository
- You also need to have Python 3 and pip installed in order to run the program
- Using pip, install the NetworkX package
- Finally, run `stats.py`

I hope that helps. If you need more specific instructions on any of those steps please refer to their respective docs as they are very informative.

The program itself is pretty straightforward with descriptive variable names and comments and print statements throughout and I went into detail on the output in the readme. If you run into any specific questions though, let me know and I can try to help you out.

Feel free to use or modify my code (credit or a citation would of course be appreciated)

**Comment by baazouziwiem** [comment]
you can send me a code that allows graphic representation of your dataset
(epinions_small.csv) if you have and with your availability, I really need
you to help me an algorithm that allows me to calculate the semilarity
based on trust (MoleTrust) and thank you very much




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
26/04/19
à 03:24:35

**Comment by robjweiss** [comment]
Unfortunately, I don't have a graphical representation of the data.

If you have any specific questions about the algorithm I can try to help.
